# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-05-12 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='stm32',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=b'', max_length=32)),
                ('time', models.CharField(default=b'', max_length=32)),
                ('state', models.CharField(default=b'', max_length=32)),
                ('data', models.CharField(default=b'', max_length=32)),
            ],
        ),
    ]
