# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2019-05-24 05:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cpu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('data', models.CharField(default='', max_length=20)),
                ('time', models.CharField(default='', max_length=20)),
                ('state', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='hum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('data', models.CharField(default='', max_length=20)),
                ('time', models.CharField(default='', max_length=20)),
                ('state', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=20)),
                ('data', models.CharField(default='', max_length=20)),
                ('time', models.CharField(default='', max_length=20)),
                ('state', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='stm32',
        ),
    ]
